### ISSUE TITLE
"Failed to execute menu action. Cannot index into null array."

### ISSUE THREAD

**Issue by mscipio** [bburky/isthereanydeal-playnite#2]
Hi!
I have tried to install this extension for the first time on Playnite 10.20 (just updated to the most recent version) and I am getting a weird error and the extension doesn't seem to work at all. I just installed the extension from the add on database

![image](https://github.com/bburky/isthereanydeal-playnite/assets/17526160/44db85fe-3528-4583-ab4a-dfc807bf600e)

Any ideas what's going on?

**Comment by bburky** [comment]
Hmm, I can't think of anything that would cause that error specifically. You did select one or more games before right clicking and choosing "Add to Is There Any Deal Collection"?

Is there any chance you have a game with an empty name? I found a bug related to that that seems like a similar issue. Try this update and let me know if it fixes the issue:
https://github.com/bburky/isthereanydeal-playnite/releases/tag/v1.4.1

Otherwise, let me know if there are any isthereanydeal-playnite or PowerShell errors in the `extensions.log` or `playnite.log` files. 
They're in the Playnite user data directory (you can find it via About Playnite -> Other -> User data directory)

**Comment by mscipio** [comment]
I will check the log as soon as I have the chance, but that error appeared with everyone I tried. All of them with different names. I was trying one game at a time.

I never got to the point to actually log into IT AS either, if the can spark some ideas ...

**Comment by bburky** [comment]
This extension has been entirely rewritten to handle the ITAD site redesign. As part of the rewrite all the code changed, this specific error should no longer apply.

Let me know if you have any issues with the new version though.
